#!/usr/bin/python
# ManningsN.py
# Database Lookup Mannings N values
# Uses Pull-Down Menu
# Use HMTL POST method
# Use python language

# Import modules for CGI handling
import cgi, cgitb , time

# Create instance of FieldStorage
form = cgi.FieldStorage()

# Get inputs from fields
description = (form.getvalue('description'))

# Assign outputs from relational input
if description == "value":
    mannings = 0.0001
    reference = "citation"

# code below generated by R script 
elif description ==  " Copper, Lead, Brass, Aluminum (new) ":
    mannings =  0.002
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " PVC and plastic pipe ":
    mannings =  0.007
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Flexible Rubber Tubing - Smooth ":
    mannings =  0.07
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Stainless Steel (new) ":
    mannings =  0.0015
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Steel Commercial Pipe ":
    mannings =  0.09
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Welded Steel ":
    mannings =  0.045
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Carbon Steel (New) ":
    mannings =  0.05
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Carbon Steel (Slightly Corroded) ":
    mannings =  0.15
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Carbon Steel (Moderately Corroded) ":
    mannings =  1.0
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Carbon Steel (Badly Corroded) ":
    mannings =  3.0
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Asphalted Cast Iron ":
    mannings =  1.0
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " New Cast Iron ":
    mannings =  0.8
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Worn Cast Iron ":
    mannings =  1.5
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Rusty Cast Iron ":
    mannings =  2.5
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Galvanized Iron ":
    mannings =  0.15
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Wood Stave  ":
    mannings =  0.91
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Wood Stave, Used ":
    mannings =  1.0
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Smoothed Cement ":
    mannings =  0.3
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Ordinary Concrete ":
    mannings =  1.0
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
 
elif description ==  " Concrete - Rough, Form Marks ":
    mannings =  3.0
    reference =  " adapted from https://www.nuclear-power.net/nuclear-engineering/fluid-dynamics/major-head-loss-friction-loss/relative-roughness-of-pipe/ "
  

## End Code Build
else:
    mannings = 0.0001
    reference = "citation unknown"


# Prepare the output HTML
now = time.strftime("%c")
        
print "Content-type:text/html\r\n\r\n"
# should have two returns and line feeds
print "<html>"
print "<head>"
print "<title> Absolute Roughness Lookup using Python</title>"
print "</head>"
print "<link rel = " """ "stylesheet" """ " type = " """ "text/css" """ " href = " """ "styles.css" """ ">"
print "<style> table, th, td {border: 1px solid black;} </style>"
print "<body>"
print " Manning's N Lookup <br/> <br/> "
print " Database Last Updated 10 AUG 2020  <br/><br/>"
print " Machine name : atomickitty.ddns.net <br/>"
print " Run Date : " , now ," <br/><br/> "
print "------ DATABASE QUERY VALUES ------ <br/> "
print " Description                        = ", description ,"<br/>  "
print " Absolute Roughness (millimeters)   = ", mannings ,"<br/>  "
print " Reference                          = ", reference ,"<br/>  "
print "</body>"
print "</html>"

# end of script
